name: Build
on:
  workflow_dispatch

permissions:
  actions: write

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm i

      - name: Gatsby Cli installation
        run: npm install -g gatsby-cli

      - name: Clear existing build and cache
        run: gatsby clean
      
      - name: Gatsby Build
        run: gatsby build

      - name: Zipping the build folder
        run: |
          cd public
          zip -r public.zip *
          mv public.zip ../

      - name: Output the zipped build output
        uses: actions/upload-artifact@v4
        with: 
          name: bundles
          path: public.zip
