name: Build and Deploy
on:
  workflow_dispatch

permissions:
  actions: write

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm ci

      - name: Gatsby Cli installation
        run: npm install -g gatsby-cli

      - name: Clear existing build and cache
        run: gatsby clean
      
      - name: Gatsby Build
        run: gatsby build --prefix-paths

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          branch: gh-pages 
          folder: public
          git-config-name: AnuragReddy2000
          git-config-email: anuragreddy1000@gmail.com
