name: Build and Deploy
on:
  workflow_dispatch

permissions:
  actions: write

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: VPN setup
        run: |
          sudo apt-get update
          sudo apt install wireguard resolvconf

      - name: Key setup
        run: |
          sudo mkdir -p /etc/wireguard/keys
          sudo touch /etc/wireguard/keys/publickey /etc/wireguard/keys/privatekey
          sudo echo ${{ secrets.VPN_KEY_PUB }} >> /etc/wireguard/keys/publickey
          sudo echo ${{ secrets.VPN_KEY_PRI }} >> /etc/wireguard/keys/privatekey
          sudo echo ${{ secrets.VPN_CONF }} >> /etc/wireguard/wg0.conf
      
      - name: Start VPN
        run: sudo wg-quick up wg0

      - name: SSH trial
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          password: ${{ secrets.REMOTE_PSWD }}
                