name: Build and Deploy
on:
  workflow_dispatch

permissions:
  actions: write

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm ci

      - name: VPN setup
        run: |
          sudo apt-get update
          sudo apt install wireguard resolvconf

      - name: Key setup
        run: |
          sudo su
          sudo mkdir -p /etc/wireguard/keys
          cd /etc/wireguard/keys
          sudo umask 077

      - name: Add public key
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: publickey
          FILE_DATA: ${{ secrets.VPN_KEY_PUB }}
      
      - name: Add private key
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: privatekey
          FILE_DATA: ${{ secrets.VPN_KEY_PRI }}

      - name: Add wireguard config
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: /etc/wireguard/wg0.conf
          FILE_DATA: ${{ secrets.VPN_CONF }}
      
      - name: Start VPN
        run: sudo wg-quick up wg0

      - name: SSH trial
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          password: ${{ secrets.REMOTE_PSWD }}
                
