name: Build and Deploy
on:
  workflow_dispatch

permissions:
  actions: write

jobs:
  Attendance-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      
      - name: Install and Build
      - run: npm ci
      - run: gatsby build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages 
          folder: build 
