name: Build and Deploy
on:
  workflow_dispatch

permissions:
  actions: write

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: VPN setup
        run: |
          sudo apt-get update
          sudo apt install wireguard resolvconf

      - name: Key setup
        run: |
          sudo mkdir -p /etc/wireguard/keys
          sudo touch publickey privatekey wg0.conf
          echo ${{ secrets.VPN_KEY_PUB }} | sudo tee publickey
          echo ${{ secrets.VPN_KEY_PRI }} | sudo tee privatekey
          echo -e ${{ secrets.VPN_CONF }} | sudo tee wg0.conf

      - name: Move configs
        run: |
          sudo mv publickey /etc/wireguard/keys/
          sudo mv privatekey /etc/wireguard/keys/
          sudo mv wg0.conf /etc/wireguard/
      
      - name: Start VPN
        run: sudo wg-quick up wg0

      - name: SSH trial
        env:
          SSHPASS: ${{ secrets.REMOTE_PWSD }}
        run: |
          sudo apt-get install sshpass
          sudo sshpass -e ssh ${{ secrets.REMOTE_HOST }} -p${{ secrets.REMOTE_PORT }}
          ls -a
        
                